    ### SignUp
POST http://localhost:3000/auth/signUp
Content-Type: application/json

{
    "email":"Abood@gmail.com",
    "name":"AboodMurad",
    "password":"AboodMurad1$"
}

### LogIn
POST http://localhost:3000/auth/logIn
Content-Type: application/json

{
    "email":"Ahmad@gmail.com",
    "password":"Ahmad123$@!"
}

### Sign Out
POST http://localhost:3000/auth/signOut

### Update  
PATCH http://localhost:3000/auth/4
Content-Type: application/json

{
    "email":"Ahmad@gmail.com",
    "name":"Ahmad",
    "admin":true
}

### remove 
DELETE  http://localhost:3000/auth/4

### Who am i
GET http://localhost:3000/auth/whoami